### ISSUE TITLE
Instantly crashes

### ISSUE THREAD

**Issue by 585381** [aleksey-saenko/MusicRecognizer#12] opened 2023-11-02 22:46 UTC
When pressing tap to rec it closes with no notification.
Last version would stay open but didn't detect any songs, from the most popular artists

**Comment by aleksey-saenko** [comment] 2023-11-03 07:35
Please provide the app version number and source, for example "v1.0.1 from f-droid". It would also be helpful to provide the phone model and firmware information (at least Android version).
It's quite difficult to understand the reasons for the failure with such limited information.
I'll consider how to make troubleshooting easier, but for now, you need to check how the app records audio on your device. To do this, turn off the internet and launch recognition. The app will save the recording to the queue, and you can listen it. Please let me know what you hear. Is the recording around 10 seconds in length? How is the quality?
If there is no any sound, for Android 12 and higher, it's useful to check that microphone access is not restricted in the notification drawer. In general, you need to ensure that the microphone on the device is functioning properly.

**Comment by Akruidenberg** [comment] 2023-11-03 17:45
Same for me. Version 1.0.1 from fdroid. Lineageos 20, oneplus 6

**Comment by DehGit** [comment] 2023-11-03 20:27
Same for me. V 1.0.1 from F-Droid.
When online tapping "recognize" causes app to crash instantly.
When offline it records without crashing and saves it in the recognition queue where it can be played back correctly. When online again it tries to recognize the queued recording without crashing.
Same behavior with or without API token.

**Comment by aleksey-saenko** [comment] 2023-11-04 09:20
@ltguillaume Thanks for providing the logs. In your case, the issue is the same as #6 . This bug fix will be included in v1.1.0, which should appear on F-Droid in the next few days. As I suspect this bug has caused crashes for others as well.

@DehGit Yes, I can confirm that the app stops working with the proper token. I suspect that this was caused by the protection system of the AudD service (see #13 ). The app should have some identifier to help differentiate it from malicious behavior. I hope that in future releases starting from v1.1.1, it will start to work fine.

**Comment by aleksey-saenko** [comment] 2023-11-04 13:26
@ltguillaume 
ServiceManager, for some reasons, indicates that the permissions android.permission.CAPTURE_AUDIO_OUTPUT and android.permission.CAPTURE_AUDIO_HOTWORD are denied for this app. However, these permissions are only allowed for system apps and are not accessible to regular third-party applications. Audile never asks for these permissions (they are not even declared in the manifest), as android.permission.RECORD_AUDIO is sufficient for audio recording. You can ignore these messages, they do not affect the application's functionality.

**Comment by aleksey-saenko** [comment] 2023-11-11 08:48
The bug fix was added in version 1.1.0, see #6 .

**Closed by aleksey-saenko** 2023-11-11 08:48 UTC
